### ISSUE TITLE
refresh should remember latest choice

### ISSUE THREAD

**Issue by litzvi** [litzvi/avc-beta#572]
Would be really continent if refresh will return me to exactly the same page with date range choice.
Same goes when landing back to the report after add/edit.

**Comment by mei309** [comment]
refresh done
when doing add/edit the piece is actually destroyed so keeping it can cause problems with when to stop keeping that information of the filters. if you thing its important i will do it but in my opinion it doesn't seem to be important.

**Comment by mei309** [comment]
on refresh i dont see a reason for it since what new information you trying to get on refresh (its a report?? 
i can do but keeping all the table filters is quite difficult (the date range is easy but doing only that would not be consistent)
all the point i know in refresh is getting to a new page without all filters or to get new data (that in our case i dont think this is the reason <maybe you using that for testing>)

**Comment by litzvi** [comment]
The problem is the arbitrary defaults.
It comes up when I'm using it all the time.
for example: I'm going over august reports and checking different pos. Every time i check a po I need to choose a month again because it's going back to the last 2 weeks.
It's just an example..
try it and you will feel.

**Comment by litzvi** [comment]
I just called it refresh.. I meant after opening and for details and closing.

**Comment by mei309** [comment]
https://user-images.githubusercontent.com/58453503/132878457-09fb1a1d-a8a7-4e2d-9d92-9862692a3285.mp4

**Comment by mei309** [comment]
it looses the filters only in case of doing a management job or edit

**Comment by litzvi** [comment]
can't see the video

**Comment by litzvi** [comment]
> it looses the filters only in case of doing a management job or edit

yes. I need to press edit to see what they filled in.
